### ISSUE TITLE
port chart-kube-lego to gitlab

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/chart-kube-lego#8]
- [ ]  Follow [instructions](https://github.com/samsung-cnct/solas/blob/master/docs/gitlab.md) to  edit`.gitlab-ci.yml` from [template](https://github.com/samsung-cnct/solas-chart/blob/master/.gitlab-ci.yml) - overwrite the current file to have it match new conventions
- [ ] also create `build/build.sh` and `build/test.sh` according to instructions
- [ ] make build.sh and test.sh executable
- [ ] submit initial PR to make next steps possible
- [ ] create secret variable in gitlab
- [ ] add pipeline status badge to README
- [ ] Remove the `build/Jenkinsfile` in the current repo.
- [ ] When PR has merged, make sure that new image is being created on quay. Afterwards,  please head back to the [umbrella ticket](https://github.com/samsung-cnct/issues/issues/89) and check off the `chart-kube-lego`

**Comment by oneilcin** [comment]
https://github.com/samsung-cnct/chart-kube-lego/pull/9

**Comment by oneilcin** [comment]
https://github.com/samsung-cnct/chart-kube-lego/pull/9
https://github.com/samsung-cnct/chart-kube-lego/pull/10
